# Generated by Django 3.1.1 on 2020-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('add', models.CharField(max_length=200)),
                ('mobno', models.CharField(max_length=10)),
                ('adhrno', models.CharField(max_length=12)),
                ('passs', models.CharField(max_length=8)),
                ('rpass', models.CharField(max_length=8)),
            ],
        ),
    ]
