# Generated by Django 3.1.1 on 2020-11-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='mobno',
            new_name='rmobno',
        ),
    ]
