# Generated by Django 3.1.3 on 2020-11-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0002_auto_20201106_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='LRecruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobno', models.CharField(max_length=10)),
                ('lpass', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='adhrno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='recruiter',
            table='rojgaar_recruiter',
        ),
    ]
