# Generated by Django 3.1.3 on 2020-11-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0003_auto_20201125_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiter',
            new_name='SRecruiter',
        ),
        migrations.AlterModelTable(
            name='lrecruiter',
            table='rojgaar_lrecruiter',
        ),
    ]
