# Generated by Django 3.1.3 on 2020-11-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0004_auto_20201127_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LRecruiter',
        ),
        migrations.AlterModelTable(
            name='srecruiter',
            table=None,
        ),
    ]
