# Generated by Django 3.1.3 on 2020-11-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0005_auto_20201127_2215'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='srecruiter',
            table='rojgaar_recruiter',
        ),
    ]
