# Generated by Django 3.1.3 on 2020-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0006_auto_20201127_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='LRecruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rmobno', models.CharField(max_length=10)),
                ('passs', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'rojgaar_lrecruiter',
            },
        ),
    ]
