# Generated by Django 3.1.3 on 2020-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0007_lrecruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LJobseeker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rmobno', models.CharField(max_length=10)),
                ('passs', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'rojgaar_ljobseeker',
            },
        ),
        migrations.CreateModel(
            name='SJobseeker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('add', models.CharField(max_length=200)),
                ('rmobno', models.CharField(max_length=10)),
                ('adhrno', models.CharField(max_length=15)),
                ('passs', models.CharField(max_length=8)),
                ('rpass', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'rojgaar_sjobseeker',
            },
        ),
        migrations.AlterModelTable(
            name='srecruiter',
            table='rojgaar_srecruiter',
        ),
    ]
