# Generated by Django 3.1.3 on 2020-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0008_auto_20201128_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sjobseeker',
            old_name='fname',
            new_name='jname',
        ),
    ]
