# Generated by Django 3.1.3 on 2020-12-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0009_auto_20201128_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jtitle', models.CharField(max_length=30)),
                ('jobregion', models.CharField(max_length=100)),
                ('jadd', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=50)),
                ('jobcat', models.CharField(max_length=100)),
                ('noofopen', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=5)),
                ('salary', models.IntegerField()),
                ('jstime', models.IntegerField()),
                ('jetime', models.IntegerField()),
                ('jobdes', models.CharField(max_length=500)),
                ('comname', models.CharField(max_length=100)),
                ('comtagline', models.CharField(max_length=200)),
                ('comdes', models.CharField(max_length=500)),
                ('comimg', models.ImageField(upload_to='')),
                ('agree', models.CharField(max_length=200)),
            ],
        ),
    ]
