# Generated by Django 3.1.3 on 2020-12-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0010_postjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='comimg',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='jobcat',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='jobregion',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='jobtype',
        ),
        migrations.AlterModelTable(
            name='postjob',
            table='rojgaar_postjob',
        ),
    ]
