# Generated by Django 3.1.3 on 2020-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0012_auto_20201204_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lrecruiter',
            old_name='lrmobno',
            new_name='rmobno',
        ),
        migrations.AlterField(
            model_name='postjob',
            name='jetime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='jstime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='noofopen',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='salary',
            field=models.CharField(max_length=10),
        ),
    ]
