# Generated by Django 3.1.3 on 2020-12-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0014_auto_20201204_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ljobseeker',
            old_name='jrmobno',
            new_name='rmobno',
        ),
        migrations.RenameField(
            model_name='sjobseeker',
            old_name='jrmobno',
            new_name='rmobno',
        ),
    ]
