# Generated by Django 3.1.3 on 2020-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0016_auto_20201205_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='jobcat',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
