# Generated by Django 3.1.3 on 2020-12-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0017_postjob_jobcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='jobtype',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
