# Generated by Django 3.1.3 on 2020-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0018_postjob_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(max_length=50)),
                ('jsadd', models.CharField(max_length=100)),
                ('jmobno', models.CharField(max_length=10)),
                ('qual', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=100)),
            ],
        ),
    ]
