# Generated by Django 3.1.3 on 2020-12-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0019_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='rmobno',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ljobseeker',
            name='rmobno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rojgaar.sjobseeker'),
        ),
        migrations.AlterField(
            model_name='lrecruiter',
            name='rmobno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sjobseeker',
            name='rmobno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='srecruiter',
            name='rmobno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='jobprofile',
            table='rojgaar_jobprofile',
        ),
    ]
