# Generated by Django 3.1.3 on 2020-12-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0020_auto_20201225_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljobseeker',
            name='rmobno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lrecruiter',
            name='rmobno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sjobseeker',
            name='rmobno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='srecruiter',
            name='rmobno',
            field=models.CharField(max_length=10),
        ),
    ]
