# Generated by Django 3.1.3 on 2020-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0021_auto_20201225_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='rmobno',
            field=models.CharField(max_length=10),
        ),
    ]
