# Generated by Django 3.1.3 on 2020-12-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0022_auto_20201225_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='rmobno',
        ),
    ]
