# Generated by Django 3.1.3 on 2020-12-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0023_remove_postjob_rmobno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostJob',
        ),
    ]
