# Generated by Django 3.1.3 on 2020-12-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0027_auto_20201225_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostJob',
            new_name='PostaJob',
        ),
        migrations.AlterModelTable(
            name='postajob',
            table='rojgaar_postajob',
        ),
    ]
