# Generated by Django 3.1.3 on 2020-12-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0029_auto_20201227_1114'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posjob',
            table='rojgaar_postjob',
        ),
    ]
