# Generated by Django 3.1.3 on 2020-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0030_auto_20201227_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='myimg',
            field=models.ImageField(blank=True, null=True, upload_to='imges/'),
        ),
    ]
