# Generated by Django 3.1.3 on 2020-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rojgaar', '0031_jobprofile_myimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLRecruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rmobno', models.CharField(max_length=10)),
                ('passs', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'rojgaar_mlrecruiter',
            },
        ),
        migrations.CreateModel(
            name='MSRecruiter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('add', models.CharField(max_length=200)),
                ('rmobno', models.CharField(max_length=10)),
                ('adhrno', models.CharField(max_length=15)),
                ('passs', models.CharField(max_length=8)),
                ('rpass', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'rojgaar_msrecruiter',
            },
        ),
        migrations.AlterModelTable(
            name='lrecruiter',
            table='rojgaar_lrecruiter',
        ),
    ]
